import { Correlation } from '@ibvap/shared';

export const INITIAL_DEMO_CORRELATIONS: Correlation[] = [
  {
    id: 'CORR-EVT-CAM01-101-EVT-CAM02-201',
    sourceEventId: 'EVT-CAM01-101',
    targetEventId: 'EVT-CAM02-201',
    sourceCameraId: 'CAM-01',
    targetCameraId: 'CAM-02',
    relationshipType: 'ENTRY_TO_CORRIDOR',
    timeDeltaSeconds: 4.2,
    score: 0.88,
    confidence: 0.88,
    state: 'candidate',
    reason: 'Topology path "ENTRY_TO_CORRIDOR" matched with delta 4.2s in [2s, 15s]',
    factors: {
      topologyMatch: true,
      temporalMatch: true,
      directionMatch: true,
      eventTypeMatch: true,
      timeDeltaSeconds: 4.2,
      minAllowedTimeSeconds: 2,
      maxAllowedTimeSeconds: 15,
      sourceEventType: 'LINE_CROSSING',
      targetEventType: 'ZONE_ENTRY',
    },
    explanation:
      'Event EVT-CAM01-101 on CAM-01 (LINE_CROSSING) precedes EVT-CAM02-201 on CAM-02 (ZONE_ENTRY) by 4.2s. This fits the configured travel window (2s–15s) for path "ENTRY_TO_CORRIDOR". Movement direction and event types are consistent.',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'CORR-EVT-CAM02-201-EVT-CAM03-301',
    sourceEventId: 'EVT-CAM02-201',
    targetEventId: 'EVT-CAM03-301',
    sourceCameraId: 'CAM-02',
    targetCameraId: 'CAM-03',
    relationshipType: 'CORRIDOR_TO_STERILE_ZONE',
    timeDeltaSeconds: 5.8,
    score: 0.92,
    confidence: 0.92,
    state: 'accepted',
    reason: 'Topology path "CORRIDOR_TO_STERILE_ZONE" matched with delta 5.8s in [2s, 18s]',
    factors: {
      topologyMatch: true,
      temporalMatch: true,
      directionMatch: true,
      eventTypeMatch: true,
      timeDeltaSeconds: 5.8,
      minAllowedTimeSeconds: 2,
      maxAllowedTimeSeconds: 18,
      sourceEventType: 'ZONE_ENTRY',
      targetEventType: 'DWELL',
    },
    explanation:
      'Event EVT-CAM02-201 on CAM-02 (ZONE_ENTRY) precedes EVT-CAM03-301 on CAM-03 (DWELL) by 5.8s. This fits the configured travel window (2s–18s) for path "CORRIDOR_TO_STERILE_ZONE". Movement direction and event types are consistent.',
    reviewedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    reviewedBy: 'Watch Commander (Duty Officer)',
    reviewNote: 'Corroborates perimeter approach corridor breach preceding sterile buffer dwell.',
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'CORR-EVT-CAM05-501-EVT-CAM03-301',
    sourceEventId: 'EVT-CAM05-501',
    targetEventId: 'EVT-CAM03-301',
    sourceCameraId: 'CAM-05',
    targetCameraId: 'CAM-03',
    relationshipType: 'PERIMETER_TO_STERILE_ZONE',
    timeDeltaSeconds: 3.5,
    score: 0.85,
    confidence: 0.85,
    state: 'candidate',
    reason: 'Topology path "PERIMETER_TO_STERILE_ZONE" matched with delta 3.5s in [2s, 15s]',
    factors: {
      topologyMatch: true,
      temporalMatch: true,
      directionMatch: true,
      eventTypeMatch: true,
      timeDeltaSeconds: 3.5,
      minAllowedTimeSeconds: 2,
      maxAllowedTimeSeconds: 15,
      sourceEventType: 'LINE_CROSSING',
      targetEventType: 'DWELL',
    },
    explanation:
      'Event EVT-CAM05-501 on CAM-05 (LINE_CROSSING) precedes EVT-CAM03-301 on CAM-03 (DWELL) by 3.5s. This fits the configured travel window (2s–15s) for path "PERIMETER_TO_STERILE_ZONE". Movement direction and event types are consistent.',
    createdAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
  },
];
